version: '3'
services:
  activemq:
    image: webcenter/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      - ACTIVEMQ_NAME=production.queue
      - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  app:
    image: rafaelpieri/springjms-activemq:latest
    ports:
      - 8080:8080
    depends_on:
      - activemq
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - ACTIVEMQ_HOST=activemq