version: '2'
services:
  activemq-service:
    image: webcenter/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      - ACTIVEMQ_NAME=helloword.queue
      - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    volumes:
      - /container_data/activemq/data:/data/activemq
      - /container_data/activemq/log:/var/log/activemq
  mysql-database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  app:
    image: spring-jms-active/openjdk-8:latest
    ports:
      - 8080:8080
    depends_on:
      - activemq-service
      - mysql-database
    environment:
      - MYSQL_HOST=mysql-database
      - ACTIVEMQ_HOST=activemq-service