spring:
  application:
    name: spring-jms-activemq'
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:activemqDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

activemq:
  broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
  in-memory: true
  non-blocking-redelivery: true
  queue:
    name: development.queue

swagger:
  title: Spring JMS with ActiveMQ
  description: The application uses Spring JMS template to publish and consume messages from ActiveMQ.
  contact:
    name: Rafael De Pieri Barbosa
  version: 0.0.1

---

spring:
  profiles: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/activemqDB?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

activemq:
  broker-url: tcp://${ACTIVEMQ_HOST}:61616
  queue:
    name: production.queue